default: &default
    facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
    facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
    cognito_client_id: <%= ENV["COGNITO_CLIENT_ID"] %>
    cognito_client_secret: <%= ENV["COGNITO_CLIENT_SECRET"] %>
    cognito_aws_region: <%= ENV["COGNITO_AWS_REGION"] %>
    cognito_user_pool_id: <%= ENV["COGNITO_USER_POOL_ID"] %>
    cognito_user_pool_site: <%= ENV["COGNITO_USER_POOL_SITE"] %>

# Make the rest of your groups inherit from default
development:
    <<: *default

test:
    <<: *default

production:
    <<: *default
